language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
os:
  - linux
  - osx
install: ['pip install tox-travis tox pytest pytest-django pytest-cov django-ckeditor']
script: ['tox']
