language: python
python: ['2.7', '3.5']
matrix:
  include:
  - python: 3.5
    dist: xenial
  - python: 3.6
    dist: xenial
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
sudo: false
install: ['pip install tox-travis tox pytest pytest-django pytest-cov django-ckeditor']
script: ['tox']
